# Generated by Django 4.1.7 on 2023-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
